-- S12 — Snowball / postupně rostoucí zvyky + podcviky
-- Vlož celé do Supabase SQL editoru a spusť (SQL Editor → New query → Run).
-- Skript je idempotentní — lze pustit opakovaně bez újmy.

-- 1) Snowball sloupce na habits
--    habit_type: 'standard' | 'snowball'
--    base_target: výchozí (minimální) denní cíl
--    step_value: o kolik se cíl navýší při každém kroku
--    interval_days: po kolika dnech se cíl navyšuje (např. 21)
--    last_increase_at: datum posledního navýšení (kotva pro výpočet dalšího)
alter table public.habits add column if not exists habit_type text not null default 'standard';
alter table public.habits add column if not exists base_target numeric;
alter table public.habits add column if not exists step_value numeric;
alter table public.habits add column if not exists interval_days integer;
alter table public.habits add column if not exists last_increase_at date;

-- 2) Podcviky — řádky pod hlavním zvykem (např. Cvičení → kliky/dřepy/sedlehy)
create table if not exists public.habit_subitems (
  id bigint generated by default as identity primary key,
  habit_id bigint not null references public.habits(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  target numeric not null default 1,
  unit text not null default '',
  position integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists habit_subitems_habit_id_idx on public.habit_subitems(habit_id);
create index if not exists habit_subitems_user_id_idx on public.habit_subitems(user_id);

-- 3) Denní hodnoty podcviků (obdoba habit_progress)
create table if not exists public.habit_subitem_progress (
  id bigint generated by default as identity primary key,
  subitem_id bigint not null references public.habit_subitems(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  value numeric not null default 0,
  unique (subitem_id, user_id, date)
);

create index if not exists habit_subitem_progress_user_date_idx
  on public.habit_subitem_progress(user_id, date);

-- 4) RLS — uživatel vidí a mění jen své řádky
alter table public.habit_subitems enable row level security;
alter table public.habit_subitem_progress enable row level security;

drop policy if exists "Users manage own habit_subitems" on public.habit_subitems;
create policy "Users manage own habit_subitems" on public.habit_subitems
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users manage own habit_subitem_progress" on public.habit_subitem_progress;
create policy "Users manage own habit_subitem_progress" on public.habit_subitem_progress
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
