-- S15 — Kalendář: tabulka events
-- Vlož celé do Supabase SQL editoru a spusť (SQL Editor → New query → Run).
-- Skript je idempotentní — lze pustit opakovaně bez újmy.

-- Události kalendáře: date + volitelné časy (start_time/end_time null = celodenní)
create table if not exists public.events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  description text,
  date date not null,
  start_time time,
  end_time time,
  created_at timestamptz not null default now()
);

create index if not exists events_user_date_idx on public.events(user_id, date);

-- RLS — uživatel vidí a mění jen své události
alter table public.events enable row level security;

drop policy if exists "Users manage own events" on public.events;
create policy "Users manage own events" on public.events
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
