-- S16 — Push notifikace: nastavení u zvyku + push subscriptions
-- Vlož celé do Supabase SQL editoru a spusť (SQL Editor → New query → Run).
-- Skript je idempotentní — lze pustit opakovaně bez újmy.

-- ČÁST A — schéma (spustit hned)

-- Nastavení připomínky u zvyku: zapnuto + čas (lokální čas uživatele,
-- vyhodnocuje ho Edge Function v zóně Europe/Prague).
alter table public.habits add column if not exists notify boolean not null default false;
alter table public.habits add column if not exists notify_time time;
-- Deduplikace: datum, kdy byla připomínka naposledy odeslána (max 1× denně).
alter table public.habits add column if not exists last_notified_date date;

-- Web push subscriptions prohlížečů uživatele (jeden řádek na zařízení/prohlížeč).
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  created_at timestamptz not null default now()
);

create index if not exists push_subscriptions_user_idx on public.push_subscriptions(user_id);

alter table public.push_subscriptions enable row level security;

drop policy if exists "Users manage own push subscriptions" on public.push_subscriptions;
create policy "Users manage own push subscriptions" on public.push_subscriptions
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ČÁST B — cron. APLIKOVÁNO 2026-06-12 (job `send-habit-notifications` aktivní,
-- viz `select * from cron.job;`). Níže ponecháno pro referenci / re-aplikaci;
-- před spuštěním nahraď <ANON_KEY> skutečným anon klíčem projektu
-- (Settings → API → anon public).

-- create extension if not exists pg_cron;
-- create extension if not exists pg_net;
--
-- do $$ begin
--   perform cron.unschedule('send-habit-notifications');
-- exception when others then null; end $$;
--
-- select cron.schedule(
--   'send-habit-notifications',
--   '*/5 * * * *',
--   $$
--   select net.http_post(
--     url := 'https://cqhggjhidxmtmnunhzjx.supabase.co/functions/v1/send-habit-notifications',
--     headers := jsonb_build_object(
--       'Content-Type', 'application/json',
--       'Authorization', 'Bearer <ANON_KEY>'
--     ),
--     body := '{}'::jsonb
--   );
--   $$
-- );
